# Generated by Django 2.2 on 2020-10-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='spam',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
